### ISSUE TITLE
Alarm doesn't vibrate?

### ISSUE THREAD

**Issue by hirozed** [AsteroidOS/meta-wren-hybris#3]
Following in the footsteps of [this closed request in asteroid-alarmclock](https://github.com/AsteroidOS/asteroid-alarmclock/issues/6), I'm noticing that the alarm app doesn't vibrate at the desired time.  I just installed AsteroidOS, so I'm not sure if I missed a setting, or if it hasn't been implemented.

Let me know if you would like me to do any additional troubleshooting.

-Jim

**Comment by FlorentRevest** [comment]
Does the watch vibrate if you go to the quicksettings (on top of the watchface) and tap the vibration icon?
This is to help us investigate is haptic support is broken or if it's a problem waking up the watch.

**Comment by hirozed** [comment]
Hello,

Yes, clicking on vibrate icon in quick settings does make the watch vibrate. Notifications and bluetooth connecting/disconnecting notices also kicks off the haptics.

Also, the alarm specifically does turn on the screen at the appropriate time, it just doesn't vibrate.  It makes a good effort, but I can't see to well with my eyes closed.  :smile: 

Thank you for looking into it.

-Jim

**Comment by FlorentRevest** [comment]
Mhhhh... interesting. If the watch wakes up, it should work. Could you send logs of journalctl -u user@1000 --no-pager as root on the watch?
Also, maybe you could replicate the problem while using ngfclient (or ngf-client, I can't remember) and then something like "play alarm" and report if the watch vibrates

**Comment by hirozed** [comment]
Sure thing. I'll give it a shot.
Just to confirm wren is the smaller Zenwatch 2, correct?  I want to make sure I installed the correct ROM on there.

**Comment by FlorentRevest** [comment]
I'm not entirely sure which one is which but if it boots, it's the right ROM ;)

**Comment by hirozed** [comment]
Hi Florent,

I've put a copy of the log on my personal [Pastebin](https://jim.reevior.com/paste/paste.php?id=10).  Let me know if it makes any sense.
I also ran the "play alarm" command you requested
```
root@wren:ceres# ngf-client "play alarm"
simple ngf client
> PLAY (event=alarm, event_id=1)
> 
Playing (event_id=1)
> 
Failed (event_id=1)
```
Let me know if there is anything further to troubleshoot.
